service: test-nest

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  httpApi:
    id: v6n1hqh675

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          method: GET
          path: /
      - httpApi:
          method: GET
          path: /add
