service: test-nest

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  httpApi:
    id: 65m29tpuo2

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          method: GET
          path: /
      - httpApi:
          method: GET
          path: /add
      - httpApi:
          method: GET
          path: /addd
      - httpApi:
          method: POST
          path: /test-post

plugins:
  - serverless-offline