name: Deploy to Amazon Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Create a production build
      run: npm run build
    - name: Install only production dependencies
      run: rm -rf node_mudules && npm install --only=prod
    - name: configure an aws cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: eu-west-1
    - name: install serversell
      run: npm i -g serverless
    - name: deploy by serverless
      run: sls deploy
